# Database configuration.
database:
  logger:
    level:  "all"
    stdout: true

  default:
    link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test?loc=Local&parseTime=true"
    debug: true


# Logger configuration.
logger:
  level : "all"
  stdout: true